spring.datasource.url=jdbc:mysql://localhost:3306/kce
spring.datasource.username=root
spring.datasource.password=Rakesh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8070

# File Uploads
file.upload-dir=sb-backend/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Secret (should be in env var in production, but hardcoded for now as per request)
jwt.secret=6d09ea0c22ba6fa65d4607ea4c34d93dd4aa0f90b6f23d19f0e0272a393be162bad094f0a2df6e2b731d940dcc415ad15d04b9264cf482ce012f0019a28f46b2

razorpay.key.id=rzp_test_SUJwF4qlfTeRvS
razorpay.key.secret=1hY78SBeQrXeHSD4CK2nx3od